/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
    implementation("org.antlr:antlr4:4.9.1")

}

sourceSets {
    main {
        java {
            setSrcDirs(listOf("src/main/java","src/main/gen"))
        }
    }
}

application {
    // Define the main class for the application.
    mainClass.set("compiler.Test")
}

tasks.test {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    }
